Escriba un programa NumPy para extraer todos los elementos de la primera y
cuarta columna de una matriz dada (4x4).


In [53]:
import numpy as np

matriz = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(matriz)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Imprime la transpuesta 1 y 4 de la matriz.

In [60]:
print(matriz.T[0])
print(matriz.T[3])

[ 1  5  9 13]
[ 4  8 12 16]
