Escriba un programa NumPy para calcular la suma de todas las columnas de una
matriz 2D NumPy

In [48]:
import numpy as np

filas = (input("Ingrese el número de filas: "))
matriz = np.zeros((int(filas), 8))
print(matriz)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


Genera numeros aleatorios de 0 a 100

In [49]:
for i in range(0, int(filas)):
    matriz[i][0] = i + 1
    for j in range(1, 8):
        matriz[i][j] = np.random.randint(1, 100)
    print(matriz[i])

[ 1. 61. 27. 32. 76. 55. 17. 95.]
[ 2. 91. 83. 89. 12. 82. 28. 71.]
[ 3. 36.  6.  9. 79.  1. 85. 82.]
[ 4. 26. 28. 11. 44. 32. 76. 19.]
[ 5. 40. 13. 75. 69. 52. 88.  8.]


Imprime la suma de todas las columnas de la matriz

In [50]:
print('Suma de cada columna es:', np.sum(matriz, axis=0))

Suma de cada columna es: [ 15. 254. 157. 216. 280. 222. 294. 275.]
